# Generated by Django 2.2 on 2020-10-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers_user',
            name='Followers',
        ),
        migrations.AddField(
            model_name='followers_user',
            name='Followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nsp_project_app.User_info'),
        ),
        migrations.AlterField(
            model_name='followers_user',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Followers', to='nsp_project_app.User_info'),
        ),
    ]
