# Generated by Django 2.2 on 2020-12-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsp_project_app', '0002_auto_20201016_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=10)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=0, max_length=10, null=True)),
                ('UpdateDate', models.DateTimeField(auto_now_add=True)),
                ('Like', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='nsp_project_app.Like')),
                ('UnLike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unlike', to='nsp_project_app.UnLike')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='nsp_project_app.Comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='institute',
            name='State_Name',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='city_Name',
        ),
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='FromUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Request_Sent', to='nsp_project_app.User_info'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='ToUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendrequests', to='nsp_project_app.User_info'),
        ),
        migrations.DeleteModel(
            name='Followig_User',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.AddField(
            model_name='notification',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='nsp_project_app.FriendRequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='nsp_project_app.User_info'),
        ),
    ]
